from django.urls import path
from . import views

urlpatterns = [
    path('',views.home),
    path('users',views.users),
    path('register',views.register_),
    path('login',views.loginHandle),
    path('del/<str:pk>/',views.delete),
    path('visuals',views.visuals),
    path('elbow',views.elbow),
    path('income',views.income),
    path('gender',views.gender),
    path('spending',views.spending),
    path('data',views.data),
    path('logout',views.logout_),
    path('dataset',views.dataset_),
    path('csv_file',views.csvfile),
    path('reports',views.report_),
    path('cluster/<str:cluster>',views.cluster_),
    path('newsletter',views.newsletter_),
    path('sendnotifications/',views.notifications_),
    path('sendnotifications/<int:key>/',views.notifications1_),
    path('viewcategoryitems/',views.view_c_items),
    path('viewcategoryitems/<int:key>/',views.view_c_items1),
    path('addcategoryitems/<int:key>/',views.add_c_items),
    path('delcategoryitems/<str:key>/',views.del_c_items),
    path('addvouchers',views.addvouchers_),
    path('addvouchers/<int:key>/',views.addvouchers),
    path('delvoucher/<str:key>/',views.delvoucher),
    path('edititem/<str:key>/',views.edititem),
    path('viewproducts',views.view_products),
    path('addproducts/',views.add_products),
    path('delproduct/<str:key>/',views.edititem),
    path('del_order/<str:key>/',views.del_order),
    path('delivered/<str:pid>/',views.delivered),
    path('customer_orders/<str:pid>/',views.cust_order),
]

