# Generated by Django 4.1.4 on 2023-02-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_card_d_address_newsletter_notifications_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_price',
            field=models.IntegerField(null=True),
        ),
    ]
