# Generated by Django 4.1.4 on 2023-02-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0003_products_p_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='p_rattings',
            field=models.IntegerField(),
        ),
    ]
