# Generated by Django 4.1.4 on 2023-02-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_alter_products_p_rattings'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
