# Generated by Django 4.1.4 on 2023-02-09 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0005_products_p_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rattigns',
            new_name='rattings',
        ),
    ]
