# Generated by Django 4.1.4 on 2023-02-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0007_orders_price_orders_t_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='voucher',
            field=models.CharField(max_length=100),
        ),
    ]
