# Generated by Django 4.1.4 on 2023-02-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0010_vouchers_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='p_cat2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
