# Generated by Django 4.1.4 on 2023-02-23 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0011_products_p_cat2'),
    ]

    operations = [
        migrations.AddField(
            model_name='d_address',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estore.orders'),
        ),
        migrations.AddField(
            model_name='orders',
            name='delivery_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
