# Generated by Django 4.1.4 on 2023-02-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0012_d_address_order_orders_delivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='delivery_status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
