# Generated by Django 4.1.4 on 2023-07-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0013_alter_orders_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
