# Generated by Django 4.1.4 on 2023-10-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0014_notifications_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(max_length=10)),
                ('test2', models.IntegerField()),
            ],
        ),
    ]
