# Generated by Django 4.1.4 on 2023-10-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0015_testtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTable',
        ),
    ]
