# Generated by Django 4.1.4 on 2023-03-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MCSApp', '0002_dataset_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataset2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('income', models.IntegerField()),
                ('spending_s', models.IntegerField()),
                ('cluster', models.IntegerField(default=0)),
            ],
        ),
    ]
