# Generated by Django 4.1.4 on 2023-07-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MCSApp', '0003_dataset2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dataset2',
        ),
    ]
